name: Test branches

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
          matrix:
            node-version: [14.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        cache: npm

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: npm-${{ hashFiles('package-lock.json') }}
        restore-keys: npm-

    - name: Install dependencies
      run: npm ci --ignore-scripts

    - name: Run linter
      run: npm run lint

    - name: Run the tests and coverage 
      run: npm run test -- --coverage
