name: Deploy to S3 Production

on:
  workflow_run: 
    workflows: [Test branches]
    types:
      - completed
    branches: 
      - main

jobs:
  
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node 14.x
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
          cache: npm

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Build project
        run: npm run build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy static site to S3 bucket
        run: ${{ secrets.DEPLOY_PROD }}